---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Filters:
    - dev:
        - abbr: #
          href: https://home.sonder.io?filter=dev
          tags:
            - filter
    - ops:
        - abbr: #
          href: https://home.sonder.io?filter=ops
          tags:
            - filter
    - ent:
        - abbr: #
          href: https://home.sonder.io?filter=ent
          tags:
            - filter
    - all:
        - abbr: #
          href: https://home.sonder.io

- Tech:
    - Bitbucket:
        - abbr: BB
          href: https://bitbucket.org/sonderdev/
          tags:
            - dev
    - DataDog:
        - abbr: DD
          href: https://app.datadoghq.com/dashboard
          tags:
            - dev
    - Jenkins:
        - abbr: JK
          href: https://jenkins.shared.sondersafe.com/
          tags:
            - dev
    - Slack:
        - abbr: SL
          href: https://sonder-monitors.slack.com/ssb/redirect
          tags:
            - dev
            - ops
    - Gsuite:
        - abbr: GS
          href: https://admin.google.com/ac/home
          tags:
            - dev
    - Firebase:
        - abbr: FB
          href: https://console.firebase.google.com/
          tags:
            - dev
    - Google Cloud Console:
        - abbr: GC
          href: https://console.cloud.google.com/welcome?project=stp-prod-ad3af
          tags:
            - dev    

- Enterprise:
    - Gmail / Chat / Meet:
        - abbr: GM
          href: https://mail.google.com/a/sonder.io
    - Calendar:
        - abbr: CA
          href: https://www.google.com/calendar/hosted/sonder.io
    - Drive:
        - abbr: GD
          href: https://drive.google.com/a/sonder.io
    - Group:
        - abbr: GR
          href: https://groups.google.com/a/sonder.io
    - Confluence:
        - abbr: CF
          href: https://sonderaustralia.atlassian.net/wiki/spaces
    - JIRA:
        - abbr: JR
          href: https://sonderaustralia.atlassian.net/jira/projects
    - 1Password:
        - abbr: JR
          href: https://sonder-australia.1password.com/vaults/all/allitems

- Network:
    - Tailscale IP:
        - abbr: TI
          href: https://ip.sonder.io
    - Tailscale Admin:
        - abbr: TA
          href: https://login.tailscale.com/admin/machines
          tags:
            - dev
    - Tailscale Self Check:
        - abbr: TS
          href: https://sonderaustralia.atlassian.net/wiki/spaces/PPROJ/pages/2110523999/Tailscale+VPN+Self+Check
    - Tailscale Mac Install:
        - abbr: TT
          href: https://sonderaustralia.atlassian.net/wiki/spaces/SIT/pages/2040103116/Macbook+Pro+-+Install+Tailscale
    - Set up AWS SSO:
        - abbr: SA
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/395182708/Setting+up+AWS
          tags:
            - dev
            - ops
    - Known IPs:
        - abbr: IP
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/338199469/Infrastructure
          tags:
            - dev

- AWS:
    - AWS SSO:
        - abbr: AS
          href: https://sonderio.awsapps.com/start#/
            - dev
    - AWS StagingRegular:
        - abbr: SR
          href: https://sonderio.awsapps.com/start/#/saml/custom/889246982606%20%28Staging%29/NDQ3ODM5MzgxODUwX2lucy1lZWI3ZDQ5MWRlY2FjZDcyX3AtMDZlMjRiZTM2NTUzMmJjNA%3D%3D
          tags:
            - dev
    - AWS ProdRegular:
        - abbr: PR
          href: https://sonderio.awsapps.com/start/#/saml/custom/084023162480%20%28Production%29/NDQ3ODM5MzgxODUwX2lucy0zODMxNmM0YTc3YmQzMjYyX3AtMTMxYjY4NjlmZTFlODJiMw%3D%3D
          tags:
            - dev
    - AWS DevRegular:
        - abbr: DR
          href: https://sonderio.awsapps.com/start/#/saml/custom/758133271689%20%28Development%29/NDQ3ODM5MzgxODUwX2lucy1jOWExMDA3YjM2OWI2ZTFhX3AtNGU5OTNjYzYxNTJjMTIyNw%3D%3D
          tags:
            - dev
    - AWS ProdAdmin:
        - abbr: PA
          href: https://sonderio.awsapps.com/start/#/saml/custom/084023162480%20%28Production%29/NDQ3ODM5MzgxODUwX2lucy0zODMxNmM0YTc3YmQzMjYyX3AtZjY2MjRlNmFjNGQwMjQwNw%3D%3D
          tags:
            - dev
    - AWS StagingAdmin:
        - abbr: ST
          href: https://sonderio.awsapps.com/start/#/saml/custom/889246982606%20%28Staging%29/NDQ3ODM5MzgxODUwX2lucy1lZWI3ZDQ5MWRlY2FjZDcyX3AtMDZlMjRiZTM2NTUzMmJjNA%3D%3D
          tags:
            - dev
    - AWS DevAdmin:
        - abbr: DA
          href: https://sonderio.awsapps.com/start/#/saml/custom/889246982606%20%28Staging%29/NDQ3ODM5MzgxODUwX2lucy1lZWI3ZDQ5MWRlY2FjZDcyX3AtMWJkNTU4Y2EyMWVhNmQ5ZA%3D%3D
          tags:
            - dev
    - AWS SharedAdmin:
        - abbr: SA
          href: https://sonderio.awsapps.com/start/#/saml/custom/422209219464%20%28Shared%20Services%29/NDQ3ODM5MzgxODUwX2lucy1lN2ZhZTZhMGYyZTJlODQ4X3AtMjQ2NzJjN2JkOTcxOTUzZA%3D%3D
          tags:
            - dev
    - AWS SharedRegular:
        - abbr: SR
          href: https://sonderio.awsapps.com/start/#/saml/custom/422209219464%20%28Shared%20Services%29/NDQ3ODM5MzgxODUwX2lucy1lN2ZhZTZhMGYyZTJlODQ4X3AtZjE3OWU1ZmM5YmNlNmFjNA%3D%3D
          tags:
            - dev
    - AWS SelfhostAdmin:
        - abbr: SA
          href: https://sonderio.awsapps.com/start/#/saml/custom/422209219464%20%28Shared%20Services%29/NDQ3ODM5MzgxODUwX2lucy1lN2ZhZTZhMGYyZTJlODQ4X3AtMjQ2NzJjN2JkOTcxOTUzZA%3D%3D
          tags:
            - dev
    - AWS SelfhostRegular:
        - abbr: SR
          href: https://sonderio.awsapps.com/start/#/saml/custom/808458673781%20%28Sonder-STP2%29/NDQ3ODM5MzgxODUwX2lucy1kYjdlMDY2N2U1NDczMTk5X3AtOTA5MWE0YzU5YTk4ZjY3Zg%3D%3D
          tags:
            - dev
    - AWS AuthenticationAdmin:
        - abbr: AA
          href: https://sonderio.awsapps.com/start/#/saml/custom/868702337695%20%28Authentication%29/NDQ3ODM5MzgxODUwX2lucy02OWNmYjY0NTQ4N2EwZThhX3AtMTZiZjhmNzIxYWJjYjA1NQ%3D%3D
          tags:
            - dev
    - AWS AuthenticationRegular:
        - abbr: AR
          href: https://sonderio.awsapps.com/start/#/saml/custom/868702337695%20%28Authentication%29/NDQ3ODM5MzgxODUwX2lucy02OWNmYjY0NTQ4N2EwZThhX3AtZGZhZmE1ZjQxYjNiZGJjOQ%3D%3D
          tags:
            - dev
    - AWS BillingAdmin:
        - abbr: BA
          href: https://sonderio.awsapps.com/start/#/saml/custom/808458673781%20%28Sonder-STP2%29/NDQ3ODM5MzgxODUwX2lucy1kYjdlMDY2N2U1NDczMTk5X3AtYTMwMmFlYjQ5ZGE1ODIwMA%3D%3D
          tags:
            - dev
    - AWS SecurityAdmin:
        - abbr: BA
          href: https://sonderio.awsapps.com/start/#/saml/custom/838943510182%20%28Security%29/NDQ3ODM5MzgxODUwX2lucy1kNGQzOTM0ZDYzZGFhOWRjX3AtNTE4Nzk5Zjc3YzFjZmU1Mw%3D%3D
          tags:
            - dev
- Portals:
    - PROD Command Portal:
        - abbr: CP
          href: https://app.prod.sondersafe.com/
    - PROD Member Portal:
        - abbr: MP
          href: https://members.sonder.io/
    - Staging Command Portal:
        - abbr: CP
          href: https://app.staging.sondersafe.com/
    - Staging Member Portal:
        - abbr: MP
          href: https://mp-staging.sonder.io/
    - Dev Command Portal:
        - abbr: CP
          href: https://app.dev.sondersafe.com/
    - Dev Member Portal:
        - abbr: MP
          href: https://mp-dev.sonder.io/

- Third Party:
    - Contentful:
        - abbr: CT
          href: https://app.contentful.com/account/organizations/1mrZfaeigcwv0r9iTIBmni/teams
          tags:
            - dev
    - Tableau:
        - abbr: TB
          href: https://prod-apsoutheast-a.online.tableau.com/#/site/sonderaustralia/home
          tags:
            - dev
    - Braze:
        - abbr: BR
          href: https://dashboard.braze.com/sign_in
          tags:
            - dev
    - Planhat:
        - abbr: PH
          href: https://app.planhat.com/data/companies
          tags:
            - dev
    - Qualtircs:
        - abbr: QT
          href: https://login.qualtrics.com/login
          tags:
            - dev
    - MediRecords:
        - abbr: MR
          href: https://app.medirecords.com/login.html#
          tags:
            - dev

- Architecture:
    - Components:
        - abbr: PC
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/364088298/Production+Platform+Components+STP
          tags:
            - dev
    - Prod Domains:
        - abbr: PD
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/2089943196/PUBLIC+Domains+and+URLS
          tags:
            - dev
