---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Filters:
    - dev:
        - abbr: #
          href: https://home.sonder.io?filter=dev
          tags:
            - filter
    - ops:
        - abbr: #
          href: https://home.sonder.io?filter=ops
          tags:
            - filter
    - ent:
        - abbr: #
          href: https://home.sonder.io?filter=ent
          tags:
            - filter
    - all:
        - abbr: #
          href: https://home.sonder.io

- Tech:
    - Bitbucket:
        - abbr: BB
          href: https://bitbucket.org/sonderdev/
          tags:
            - dev
    - DataDog:
        - abbr: DD
          href: https://app.datadoghq.com/dashboard
          tags:
            - dev
    - Jenkins:
        - abbr: JK
          href: https://jenkins.shared.sondersafe.com/
          tags:
            - dev
    - Slack:
        - abbr: SL
          href: https://sonder-monitors.slack.com/ssb/redirect
          tags:
            - dev
            - ops
    - Grafana:
        - abbr: GR
          href: https://grafana.shared.sondersafe.com/
          tags:
            - dev
            - ops
    - Gsuite:
        - abbr: GS
          href: https://admin.google.com/ac/home
          tags:
            - dev
    - Firebase:
        - abbr: FB
          href: https://console.firebase.google.com/
          tags:
            - dev
    - Google Cloud Console:
        - abbr: GC
          href: https://console.cloud.google.com/welcome?project=stp-prod-ad3af
          tags:
            - dev
    - SourceGraph:
        - abbr: SG
          href: http://10.1.1.251:7080/search
          tags:
            - dev
    - Nexus:
        - abbr: NX
          href: https://nexus.shared.sondersafe.com/
          tags:
            - dev
    - SonarCLoud:
        - abbr: SC
          href: https://sonarcloud.io/organizations/sonderdev/projects?sort=analysis_date
          tags:
            - dev

- Enterprise:
    - Gmail / Chat / Meet:
        - abbr: GM
          href: https://mail.google.com/a/sonder.io
    - Calendar:
        - abbr: CA
          href: https://www.google.com/calendar/hosted/sonder.io
    - Drive:
        - abbr: GD
          href: https://drive.google.com/a/sonder.io
    - Group:
        - abbr: GR
          href: https://groups.google.com/a/sonder.io
    - Confluence:
        - abbr: CF
          href: https://sonderaustralia.atlassian.net/wiki/spaces
    - JIRA:
        - abbr: JR
          href: https://sonderaustralia.atlassian.net/jira/projects
    - 1Password:
        - abbr: JR
          href: https://sonder-australia.1password.com/vaults/all/allitems
    - SnapPass:
        - abbr: SN
          href: https://snappass.shared.sondersafe.com

- Network:
    - Tailscale IP:
        - abbr: TI
          href: https://ip.sonder.io
    - Tailscale Admin:
        - abbr: TA
          href: https://login.tailscale.com/admin/machines
          tags:
            - dev
    - Tailscale Self Check:
        - abbr: TS
          href: https://sonderaustralia.atlassian.net/wiki/spaces/PPROJ/pages/2110523999/Tailscale+VPN+Self+Check
    - Tailscale Mac Install:
        - abbr: TT
          href: https://sonderaustralia.atlassian.net/wiki/spaces/SIT/pages/2040103116/Macbook+Pro+-+Install+Tailscale
    - Set up AWS SSO:
        - abbr: SA
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/395182708/Setting+up+AWS
          tags:
            - dev
            - ops
    - Known IPs:
        - abbr: IP
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/338199469/Infrastructure
          tags:
            - dev

- AWS:
    - AWS SSO:
        - abbr: AS
          href: https://sonderio.awsapps.com/start#/
          tags:
            - dev
    
- Portals:
    - PROD Command Portal:
        - abbr: CP
          href: https://app.prod.sondersafe.com/
    - PROD Member Portal:
        - abbr: MP
          href: https://members.sonder.io/
    - Staging Command Portal:
        - abbr: CP
          href: https://app.staging.sondersafe.com/
    - Staging Member Portal:
        - abbr: MP
          href: https://mp-staging.sonder.io/
    - Dev Command Portal:
        - abbr: CP
          href: https://app.dev.sondersafe.com/
    - Dev Member Portal:
        - abbr: MP
          href: https://mp-dev.sonder.io/

- Third Party:
    - Contentful:
        - abbr: CT
          href: https://app.contentful.com/account/organizations/1mrZfaeigcwv0r9iTIBmni/teams
          tags:
            - dev
    - Tableau:
        - abbr: TB
          href: https://prod-apsoutheast-a.online.tableau.com/#/site/sonderaustralia/home
          tags:
            - dev
    - Braze:
        - abbr: BR
          href: https://dashboard.braze.com/sign_in
          tags:
            - dev
    - Planhat:
        - abbr: PH
          href: https://app.planhat.com/data/companies
          tags:
            - dev
    - Qualtircs:
        - abbr: QT
          href: https://login.qualtrics.com/login
          tags:
            - dev
    - MediRecords:
        - abbr: MR
          href: https://app.medirecords.com/login.html#
          tags:
            - dev

- Architecture:
    - Components:
        - abbr: PC
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/364088298/Production+Platform+Components+STP
          tags:
            - dev
    - Prod Domains:
        - abbr: PD
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/2089943196/PUBLIC+Domains+and+URLS
          tags:
            - dev
