---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Filters:
    - dev:
        - abbr: #
          href: https://home.sonder.io?filter=dev
          tags:
            - filter
    - ops:
        - abbr: #
          href: https://home.sonder.io?filter=ops
          tags:
            - filter
    - ent:
        - abbr: #
          href: https://home.sonder.io?filter=ent
          tags:
            - filter
    - all:
        - abbr: #
          href: https://home.sonder.io

- Tech:
    - Bitbucket:
        - abbr: BB
          href: https://bitbucket.org/sonderdev/
          tags:
            - dev
    - DataDog:
        - abbr: DD
          href: https://app.datadoghq.com/dashboard
          tags:
            - dev
    - Jenkins:
        - abbr: JK
          href: https://jenkins.shared.sondersafe.com/
          tags:
            - dev
    - Slack:
        - abbr: SL
          href: https://sonder-monitors.slack.com/ssb/redirect
          tags:
            - dev
            - ops

- Enterprise:
    - Gmail / Chat / Meet:
        - abbr: GM
          href: https://mail.google.com/a/sonder.io
    - Calendar:
        - abbr: CA
          href: https://www.google.com/calendar/hosted/sonder.io
    - Drive:
        - abbr: GD
          href: https://drive.google.com/a/sonder.io
    - Group:
        - abbr: GR
          href: https://groups.google.com/a/sonder.io
    - Confluence:
        - abbr: CF
          href: https://sonderaustralia.atlassian.net/wiki/spaces
    - JIRA:
        - abbr: JR
          href: https://sonderaustralia.atlassian.net/jira/projects
    - 1Password:
        - abbr: JR
          href: https://sonder-australia.1password.com/vaults/all/allitems

- Network:
    - Tailscale IP:
        - abbr: TI
          href: https://ip.sonder.io
    - Tailscale Self Check:
        - abbr: TS
          href: https://sonderaustralia.atlassian.net/wiki/spaces/PPROJ/pages/2110523999/Tailscale+VPN+Self+Check
    - Tailscale Mac Install:
        - abbr: TT
          href: https://sonderaustralia.atlassian.net/wiki/spaces/SIT/pages/2040103116/Macbook+Pro+-+Install+Tailscale
    - Set up AWS SSO:
        - abbr: SA
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/395182708/Setting+up+AWS
          tags:
            - dev
            - ops
    - Known IPs
        - abbr: IP
          href: https://sonderaustralia.atlassian.net/wiki/spaces/DEV/pages/338199469/Infrastructure
          tags:
            - dev

- AWS:
    - AWS SSO:
        - abbr: AS
          href: https://sonderio.awsapps.com/start#/
          tags:
            - dev
            - ops
    - AWS Staging Regular:
        - abbr: ST
          href: https://sonderio.awsapps.com/start/#/saml/custom/889246982606%20%28Staging%29/NDQ3ODM5MzgxODUwX2lucy1lZWI3ZDQ5MWRlY2FjZDcyX3AtMDZlMjRiZTM2NTUzMmJjNA%3D%3D
          tags:
            - dev
            - ops
    - AWS Production Regular:
        - abbr: SP
          href: https://sonderio.awsapps.com/start/#/saml/custom/084023162480%20%28Production%29/NDQ3ODM5MzgxODUwX2lucy0zODMxNmM0YTc3YmQzMjYyX3AtMTMxYjY4NjlmZTFlODJiMw%3D%3D
          tags:
            - dev
            - ops
- Portals:
    - Command Portal:
        - abbr: CP
          href: https://app.prod.sondersafe.com/
    - Member Portal:
        - abbr: MP
          href: https://members.sonder.io/

- Third Party:
    - Contentful:
        - abbr: CT
          href: https://app.contentful.com/account/organizations/1mrZfaeigcwv0r9iTIBmni/teams
          tags:
            - dev
    - Tableau:
        - abbr: TB
          href: https://prod-apsoutheast-a.online.tableau.com/#/site/sonderaustralia/home
          tags:
            - dev
    - Braze:
        - abbr: BR
          href: https://dashboard.braze.com/sign_in
          tags:
            - dev
    - Planhat:
        - abbr: PH
          href: https://app.planhat.com/data/companies
          tags:
            - dev
