---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

# - My First Group:
#     - My First Service:
#         href: http://localhost/
#         description: Homepage is awesome
        

# - My Second Group:
#     - My Second Service:
#         href: http://localhost/
#         description: Homepage is the best

# - My Third Group:
#     - My Third Service:
#         icon: emby.png
#         href: https://ip.sonder.io
#         description: SonderIP
#         widget:
#             type: ipsonder
#             url: https://ip.sonder.io
